### PR TITLE
Travis Support and apparently line endings

### PR DESCRIPTION
**Pull request by alama**

### CODE REVIEW

**Comment by alama** [comment]
@cyberkitsune when I checkout the code, GIT already changes the EOL

**Comment by Kyle873** [comment]
@cyberkitsune the .gitattributes will make sure that any code checked into the repository is LF'd. There should be no inconsistency issues with line endings at all.

**Comment by VariantXYZ** [comment]
@cyberkitsune @alama @Kyle873 

Files in the repo should be LF, except for xproj and sln files which should be CRLF.

We're also doing cross-platform development, so using 'auto' should be fine.

**Comment by VariantXYZ** [comment]
Wait why are we doing this in the travis implementation PR.

@alama just revert your change to gitattributes and I'll accept this PR. Line endings should be a different issue.

**Pull request merged**
